### ISSUE TITLE
Constant time equality proof

### ISSUE THREAD

**Issue by ericelliott** [thenables/pswd#4]
Hi,

I'm the maintainer of Credential. We're currently trying to harden our constant time equality check in Credential, and we're looking for a good statistics test to ensure that our timing is constant enough to thwart timing attacks.

Your experience and feedback would be very useful. Please take a look at this [proposed constant time string comparison](https://github.com/ericelliott/credential/pull/13). I'm especially interested in producing a test suite that can guarantee statistically significant constant time equality comparisons, and I believe such tests would be useful to your library, as well.

My assertion is that none of our libs are complete without a statistical proof that our constant time comparisons are constant enough to thwart actual timing attacks. See Crosby et al: 

> "We have shown that, even though the Internet induces significant timing jitter, we can reliably distinguish remote timing differences as low as 20 µs. A LAN environment has lower timing jitter, allowing us to reliably distinguish remote timing differences as small as 100 ns (possibly even smaller). These precise timing differences can be distinguished with only hundreds or possibly thousands of measurements." Crosby et al., ["Opportunities and Limits of Remote Timing Attacks"](http://www.cs.rice.edu/~dwallach/pub/crosby-timing2009.pdf)

So if we're going to implement libraries and call them secure, we need to prove it in our test suites. Wouldn't you agree? With Credential, I don't just expect people to trust that it's secure. [I'm putting my money where my mouth is.](https://github.com/ericelliott/credential/issues/8)

Because what we do in our libraries potentially impacts the personal security of millions of people, I think it's our responsibility as security library maintainers to provide assurances that we take these things seriously.

Thanks for taking security seriously,

Eric Elliott
Author, "Programming JavaScript Applications"

**Comment by jonathanong** [comment]
i don't mind changing the constant time string compare module i use if there's one better. but i don't know shit about that stuff.

**Comment by ericelliott** [comment]
I don't either. That's why I'm soliciting the community for help. I'll keep you posted on our findings. So far the TL;DR is that timing attacks are useless if you're using a decent one way hash algorithm (like pbkdf2 or bcrypt) and the attacker doesn't have access to the salts.

The general consensus has been that we should keep the constant time equality checks anyway because it can't hurt. I disagree with that. I think if they're not needed we should take them out -- but before I do that, I want to be reassured that they really aren't necessary by an expert in timing attacks.

Somebody who's an expert at actually cracking passwords, for instance. I know of a guy who is, but I haven't managed to get a response from him, yet. Do you know any experts we can ask?

**Comment by jonathanong** [comment]
nope

**Comment by ericelliott** [comment]
No worries. Thanks! =)

**Comment by jonathanong** [comment]
let me know if you have any udpates on this. closing fo rnow
